[package]
name = "parser_sample"
version = "0.1.0"
authors = ["Erlan Dumah <erlandumah@yahoo.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11.20", features = ["blocking"] }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench_parser"
harness = false
